//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     .NET Micro Framework MFSvcUtil.Exe
//     Runtime Version:2.0.00001.0001
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Text;
using System.Xml;
using Dpws.Device;
using Dpws.Device.Services;
using Ws.Services;
using Ws.Services.WsaAddressing;
using Ws.Services.Xml;
using Ws.Services.Binding;
using Ws.Services.Soap;

namespace tempuri.org
{
    
    
    public class IDomoticService : DpwsHostedService
    {
        
        private IIDomoticService m_service;
        
        public IDomoticService(IIDomoticService service, ProtocolVersion version) : 
                base(version)
        {
            // Set the service implementation properties
            m_service = service;

            // Set base service properties
            ServiceNamespace = new WsXmlNamespace("ido", "http://tempuri.org/");
            ServiceID = "urn:uuid:7c26c902-64db-4da4-95f3-bb5f6942e345";
            ServiceTypeName = "IDomoticService";

            // Add service types here
            ServiceOperations.Add(new WsServiceOperation("http://tempuri.org/IDomoticService", "insertValue"));

            // Add event sources here
        }
        
        public IDomoticService(IIDomoticService service) : 
                this(service, new ProtocolVersion10())
        {
        }
        
        public virtual WsMessage insertValue(WsMessage request)
        {
            // Build request object
            insertValueDataContractSerializer reqDcs;
            reqDcs = new insertValueDataContractSerializer("insertValue", "http://tempuri.org/");
            insertValue req;
            req = ((insertValue)(reqDcs.ReadObject(request.Reader)));

            // Create response object
            // Call service operation to process request and return response.
            insertValueResponse resp;
            resp = m_service.insertValue(req);

            // Create response header
            WsWsaHeader respHeader = new WsWsaHeader("http://tempuri.org/IDomoticService/insertValueResponse", request.Header.MessageID, m_version.AnonymousUri, null, null, null);
            WsMessage response = new WsMessage(respHeader, resp, WsPrefix.Wsdp);

            // Create response serializer
            insertValueResponseDataContractSerializer respDcs;
            respDcs = new insertValueResponseDataContractSerializer("insertValueResponse", "http://tempuri.org/");
            response.Serializer = respDcs;
            return response;
        }
    }
}
