//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     .NET Micro Framework MFSvcUtil.Exe
//     Runtime Version:2.0.00001.0001
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Xml;
using Dpws.Client;
using Dpws.Client.Discovery;
using Dpws.Client.Eventing;
using Ws.Services;
using Ws.Services.Utilities;
using Ws.Services.Binding;
using Ws.Services.Soap;
using Ws.Services.WsaAddressing;
using Ws.Services.Xml;

namespace tempuri.org
{
    
    
    public class IDomoticServiceClientProxy : DpwsClient
    {
        
        private IRequestChannel m_requestChannel = null;
        
        public IDomoticServiceClientProxy(Binding binding, ProtocolVersion version) : 
                base(binding, version)
        {

            // Set client endpoint address
            m_requestChannel = m_localBinding.CreateClientChannel(new ClientBindingContext(m_version));
        }
        
        public virtual insertValueResponse insertValue(insertValue req)
        {

            // Create request header
            String action;
            action = "http://tempuri.org/IDomoticService/insertValue";
            WsWsaHeader header;
            header = new WsWsaHeader(action, null, EndpointAddress, m_version.AnonymousUri, null, null);
            WsMessage request = new WsMessage(header, req, WsPrefix.None);

            // Create request serializer
            insertValueDataContractSerializer reqDcs;
            reqDcs = new insertValueDataContractSerializer("insertValue", "http://tempuri.org/");
            request.Serializer = reqDcs;
            request.Method = "insertValue";


            // Send service request
            m_requestChannel.Open();
            WsMessage response = m_requestChannel.Request(request);
            m_requestChannel.Close();

            // Process response
            insertValueResponseDataContractSerializer respDcs;
            respDcs = new insertValueResponseDataContractSerializer("insertValueResponse", "http://tempuri.org/");
            insertValueResponse resp;
            resp = ((insertValueResponse)(respDcs.ReadObject(response.Reader)));
            return resp;
        }
    }
}
